apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8-cluster-control-viewer
rules:
  - apiGroups: [""]
    resources: ["namespaces", "nodes", "pods", "pods/log", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8-cluster-control-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8-cluster-control-viewer
subjects:
  - kind: ServiceAccount
    name: k8-cluster-control
    namespace: k8-cluster-control